dbapi2:
    psycopg2
    
connect_args:
    - dbname=jmh
    - dbuser=jmh
    
target_schema:
    madlib

methods:
    - name: sketch
      port: extended_sql/pg_gp

    - name: profile
      port: simple_sql

    - name: bayes
      port: extended_sql/pg_gp
