###
# List of methods/modules and their dependencies:
###
modules:
    - name: array_ops
    - name: bayes
#    - name: conjugate-gradient
#      depends: ['array_ops']
#    - name: decision-tree
#      depends: ['svec','array_ops']
    - name: kmeans
      depends: ['svec']
#    - name: kernel-machines
#      depends: ['svec']
#    - name: plda
    - name: prob
#    - name: profile
#      depends: ['sketch']
#    - name: quantile 
    - name: regress
#    - name: sketch
#    - name: svd-mf
    - name: svec
