###
# List of methods/modules and their dependencies:
###
modules:
#    - name: sketch
#    - name: profile
#    - name: bayes
#    - name: k-means
#      depends: ['svec']
#    - name: kernel-machines
    - name: prob
    - name: regress
#    - name: svec
#    - name: svd-mf
#    - name: quantile 
#    - name: decision-tree
    - name: conjugate-gradient
