# List of DB Ports to compile MADlib for.
# 
# Synopsis:
# - name   : descriptive name of the new DB port
#   id     : ID of this port (used in the port specs file <id>.yml)
#   dbapi2 : Python API module for this port 
#            (DBAPI2 compliant: http://www.python.org/dev/peps/pep-0249/)
#
ports:

    - name:   PostgreSQL
      id:     postgres
      dbapi2: pygresql.pgdb

    - name:   Greenplum DB
      id:     greenplum
      dbapi2: pygresql.pgdb
