###
# List of methods and their dependencies:
###
methods:
#    - name:    sketch
#    - name: profile
#    - name: bayes
    - name:    k-means
      depends: ['svec']
#    - name: kernel-machines
#    - name: regress
    - name:    svec
#    - name: svd-mf
#    - name: quantile 
#    - name: decision-tree
#    - name: conjugate-gradient
