connect_args:
    dbname=joeh
    dbuser=joeh
    
methods:
    - name: sketch
      port: extended_sql/pg_gp

    - name: profile
      port: extended_sql/pg_gp

    - name: bayes
      port: extended_sql/pg_gp