dbapi2:
    psycopg2
    
connect_args:
    - dbname=madlib_test
    - dbuser=gpadmin
    
target_schema:
    madlib

methods:
    - name: sketch
      port: extended_sql/pg_gp

    - name: profile
      port: simple_sql

    - name: bayes
      port: extended_sql/pg_gp

    - name: k-means
      port: pg_gp

    - name: kernel-machines
      port: pg_gp

    - name: regress
      port: pg_gp

prep_flags: -DMADLIB
