dbapi2:
    pygresql.pgdb
    
# According to DB API 2.0 specification
# these are the allowed conection arguments:
#   dsn         Data source name as string
#   user        User name as string (optional)
#   password    Password as string (optional)
#   host        Hostname (optional)
#   database    Database name (optional)
connect_args:
    - host=localhost
    - database=madlib
    - user=gpadmin
    
target_schema:
    madlib

methods:
    - name: sketch
      port: extended_sql/pg_gp

    - name: profile
      port: simple_sql

    - name: bayes
      port: extended_sql/pg_gp

    - name: k-means
      port: pg_gp

    - name: kernel-machines
      port: pg_gp

    - name: regress
      port: pg_gp

prep_flags: -DMADLIB
